[build]
  command = "npm run build"  # or your build command
  publish = "src/build"      # update if your publish path is different

[build.environment]
  GO_VERSION = "1.22.3"
  PYTHON_VERSION = "3.13.3"
  RUBY_VERSION = "3.4.3"
